/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.8.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyDto {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "role")]
    pub role: i32,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl ApiKeyDto {
    pub fn new(created_at: String, id: uuid::Uuid, name: String, role: i32, updated_at: String, user_id: uuid::Uuid) -> ApiKeyDto {
        ApiKeyDto {
            created_at,
            id,
            name,
            role,
            updated_at,
            user_id,
        }
    }
}

