/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChunkReqPayload {
    /// HTML content of the chunk. This can also be plaintext. The innerText of the HTML will be used to create the embedding vector. The point of using HTML is for convienience, as some users have applications where users submit HTML content.
    #[serde(rename = "chunk_html", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub chunk_html: Option<Option<String>>,
    /// Convert HTML to raw text before processing to avoid adding noise to the vector embeddings. By default this is true. If you are using HTML content that you want to be included in the vector embeddings, set this to false.
    #[serde(rename = "convert_html_to_text", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub convert_html_to_text: Option<Option<bool>>,
    #[serde(rename = "fulltext_boost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fulltext_boost: Option<Option<Box<models::FullTextBoost>>>,
    /// Group ids are the Trieve generated ids of the groups that the chunk should be placed into. This is useful for when you want to create a chunk and add it to a group or multiple groups in one request. Groups with these Trieve generated ids must be created first, it cannot be arbitrarily created through this route.
    #[serde(rename = "group_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group_ids: Option<Option<Vec<uuid::Uuid>>>,
    /// Group tracking_ids are the user-assigned tracking_ids of the groups that the chunk should be placed into. This is useful for when you want to create a chunk and add it to a group or multiple groups in one request. If a group with the tracking_id does not exist, it will be created.
    #[serde(rename = "group_tracking_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group_tracking_ids: Option<Option<Vec<String>>>,
    /// Image urls are a list of urls to images that are associated with the chunk. This is useful for when you want to associate images with a chunk.
    #[serde(rename = "image_urls", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_urls: Option<Option<Vec<String>>>,
    /// Link to the chunk. This can also be any string. Frequently, this is a link to the source of the chunk. The link value will not affect the embedding creation.
    #[serde(rename = "link", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub link: Option<Option<String>>,
    #[serde(rename = "location", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location: Option<Option<Box<models::GeoInfo>>>,
    /// Metadata is a JSON object which can be used to filter chunks. This is useful for when you want to filter chunks by arbitrary metadata. Unlike with tag filtering, there is a performance hit for filtering on metadata.
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<serde_json::Value>>,
    /// Num value is an arbitrary numerical value that can be used to filter chunks. This is useful for when you want to filter chunks by numerical value. There is no performance hit for filtering on num_value.
    #[serde(rename = "num_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub num_value: Option<Option<f64>>,
    #[serde(rename = "semantic_boost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub semantic_boost: Option<Option<Box<models::SemanticBoost>>>,
    /// If semantic_content is present, it will be used for creating semantic embeddings instead of the innerText `chunk_html`. `chunk_html` will still be the only thing stored and always used for fulltext functionality.
    #[serde(rename = "semantic_content", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub semantic_content: Option<Option<String>>,
    /// Split avg is a boolean which tells the server to split the text in the chunk_html into smaller chunks and average their resulting vectors. This is useful for when you want to create a chunk from a large piece of text and want to split it into smaller chunks to create a more fuzzy average dense vector. The sparse vector will be generated normally with no averaging. By default this is false.
    #[serde(rename = "split_avg", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub split_avg: Option<Option<bool>>,
    /// Tag set is a list of tags. This can be used to filter chunks by tag. Unlike with metadata filtering, HNSW indices will exist for each tag such that there is not a performance hit for filtering on them.
    #[serde(rename = "tag_set", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tag_set: Option<Option<Vec<String>>>,
    /// Time_stamp should be an ISO 8601 combined date and time without timezone. It is used for time window filtering and recency-biasing search results.
    #[serde(rename = "time_stamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_stamp: Option<Option<String>>,
    /// Tracking_id is a string which can be used to identify a chunk. This is useful for when you are coordinating with an external system and want to use the tracking_id to identify the chunk.
    #[serde(rename = "tracking_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tracking_id: Option<Option<String>>,
    /// Upsert when a chunk with the same tracking_id exists. By default this is false, and the request will fail if a chunk with the same tracking_id exists. If this is true, the chunk will be updated if a chunk with the same tracking_id exists.
    #[serde(rename = "upsert_by_tracking_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub upsert_by_tracking_id: Option<Option<bool>>,
    /// Weight is a float which can be used to bias search results. This is useful for when you want to bias search results for a chunk. The magnitude only matters relative to other chunks in the chunk's dataset dataset.
    #[serde(rename = "weight", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub weight: Option<Option<f64>>,
}

impl ChunkReqPayload {
    pub fn new() -> ChunkReqPayload {
        ChunkReqPayload {
            chunk_html: None,
            convert_html_to_text: None,
            fulltext_boost: None,
            group_ids: None,
            group_tracking_ids: None,
            image_urls: None,
            link: None,
            location: None,
            metadata: None,
            num_value: None,
            semantic_boost: None,
            semantic_content: None,
            split_avg: None,
            tag_set: None,
            time_stamp: None,
            tracking_id: None,
            upsert_by_tracking_id: None,
            weight: None,
        }
    }
}

