/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChunkMetadataTypes {
    SlimChunkMetadata(Box<models::SlimChunkMetadata>),
    ChunkMetadataStringTagSet(Box<models::ChunkMetadataStringTagSet>),
    ContentChunkMetadata(Box<models::ContentChunkMetadata>),
}

impl Default for ChunkMetadataTypes {
    fn default() -> Self {
        Self::SlimChunkMetadata(Default::default())
    }
}

