/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.8.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConditionType {
    FieldCondition(Box<models::FieldCondition>),
    HasIdCondition(Box<models::HasIdCondition>),
}

impl Default for ConditionType {
    fn default() -> Self {
        Self::FieldCondition(Default::default())
    }
}

