/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CountChunkQueryResponseBody {
    #[serde(rename = "count")]
    pub count: i32,
}

impl CountChunkQueryResponseBody {
    pub fn new(count: i32) -> CountChunkQueryResponseBody {
        CountChunkQueryResponseBody {
            count,
        }
    }
}

