/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.8
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateChunkGroupData {
    /// Description to assign to the chunk_group. Convenience field for you to avoid having to remember what the group is for.
    #[serde(rename = "description")]
    pub description: String,
    /// Name to assign to the chunk_group. Does not need to be unique.
    #[serde(rename = "name")]
    pub name: String,
    /// Optional tracking id to assign to the chunk_group. This is a unique identifier for the chunk_group.
    #[serde(rename = "tracking_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tracking_id: Option<Option<String>>,
}

impl CreateChunkGroupData {
    pub fn new(description: String, name: String) -> CreateChunkGroupData {
        CreateChunkGroupData {
            description,
            name,
            tracking_id: None,
        }
    }
}

