/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSetupCheckoutSessionResPayload {
    #[serde(rename = "url")]
    pub url: String,
}

impl CreateSetupCheckoutSessionResPayload {
    pub fn new(url: String) -> CreateSetupCheckoutSessionResPayload {
        CreateSetupCheckoutSessionResPayload {
            url,
        }
    }
}

