/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CtrAnalytics {
    #[serde(rename="SearchCTRMetrics_1")]
    SearchCtrMetrics1(Box<models::SearchCtrMetrics1>),
    #[serde(rename="SearchesWithClicks")]
    SearchesWithClicks(Box<models::SearchesWithClicks>),
    #[serde(rename="SearchesWithoutClicks")]
    SearchesWithoutClicks(Box<models::SearchesWithoutClicks>),
    #[serde(rename="RecommendationCTRMetrics_1")]
    RecommendationCtrMetrics1(Box<models::RecommendationCtrMetrics1>),
    #[serde(rename="RecommendationsWithClicks")]
    RecommendationsWithClicks(Box<models::RecommendationsWithClicks>),
    #[serde(rename="RecommendationsWithoutClicks")]
    RecommendationsWithoutClicks(Box<models::RecommendationsWithoutClicks>),
}

impl Default for CtrAnalytics {
    fn default() -> Self {
        Self::SearchCtrMetrics1(Default::default())
    }
}


