/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CtrType {
    #[serde(rename = "search")]
    Search,
    #[serde(rename = "recommendation")]
    Recommendation,

}

impl ToString for CtrType {
    fn to_string(&self) -> String {
        match self {
            Self::Search => String::from("search"),
            Self::Recommendation => String::from("recommendation"),
        }
    }
}

impl Default for CtrType {
    fn default() -> CtrType {
        Self::Search
    }
}

