/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeprecatedSearchOverGroupsResponseBody {
    #[serde(rename = "group_chunks")]
    pub group_chunks: Vec<models::GroupScoreChunk>,
    #[serde(rename = "total_chunk_pages")]
    pub total_chunk_pages: i64,
}

impl DeprecatedSearchOverGroupsResponseBody {
    pub fn new(group_chunks: Vec<models::GroupScoreChunk>, total_chunk_pages: i64) -> DeprecatedSearchOverGroupsResponseBody {
        DeprecatedSearchOverGroupsResponseBody {
            group_chunks,
            total_chunk_pages,
        }
    }
}

