/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.8
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditMessageData {
    /// Whether or not to highlight the citations in the response. If this is set to true or not included, the citations will be highlighted. If this is set to false, the citations will not be highlighted. Default is true.
    #[serde(rename = "highlight_citations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub highlight_citations: Option<Option<bool>>,
    /// The delimiters to use for highlighting the citations. If this is not included, the default delimiters will be used. Default is `[\".\", \"!\", \"?\", \"\\n\", \"\\t\", \",\"]`.
    #[serde(rename = "highlight_delimiters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub highlight_delimiters: Option<Option<Vec<String>>>,
    /// The sort order of the message to edit.
    #[serde(rename = "message_sort_order")]
    pub message_sort_order: i32,
    /// The model to use for the assistant generative inferences. This can be any model from the openrouter model list. If no model is provided, the gpt-3.5-turbo will be used.~
    #[serde(rename = "model", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model: Option<Option<String>>,
    /// The new content of the message to replace the old content with.
    #[serde(rename = "new_message_content")]
    pub new_message_content: String,
    /// Whether or not to stream the response. If this is set to true or not included, the response will be a stream. If this is set to false, the response will be a normal JSON response. Default is true.
    #[serde(rename = "stream_response", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stream_response: Option<Option<bool>>,
    /// The id of the topic to edit the message at the given sort order for.
    #[serde(rename = "topic_id")]
    pub topic_id: uuid::Uuid,
}

impl EditMessageData {
    pub fn new(message_sort_order: i32, new_message_content: String, topic_id: uuid::Uuid) -> EditMessageData {
        EditMessageData {
            highlight_citations: None,
            highlight_delimiters: None,
            message_sort_order,
            model: None,
            new_message_content,
            stream_response: None,
            topic_id,
        }
    }
}

