/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.10.9
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventReturn {
    #[serde(rename = "events")]
    pub events: Vec<models::Event>,
    #[serde(rename = "page_count")]
    pub page_count: i32,
}

impl EventReturn {
    pub fn new(events: Vec<models::Event>, page_count: i32) -> EventReturn {
        EventReturn {
            events,
            page_count,
        }
    }
}

