/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.8.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetChunksData {
    #[serde(rename = "ids")]
    pub ids: Vec<uuid::Uuid>,
}

impl GetChunksData {
    pub fn new(ids: Vec<uuid::Uuid>) -> GetChunksData {
        GetChunksData {
            ids,
        }
    }
}

