/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllTagsResponse {
    #[serde(rename = "tags")]
    pub tags: Vec<models::TagsWithCount>,
    #[serde(rename = "total")]
    pub total: i64,
}

impl GetAllTagsResponse {
    pub fn new(tags: Vec<models::TagsWithCount>, total: i64) -> GetAllTagsResponse {
        GetAllTagsResponse {
            tags,
            total,
        }
    }
}

