/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupScoreSlimChunks {
    #[serde(rename = "group_id")]
    pub group_id: uuid::Uuid,
    #[serde(rename = "metadata")]
    pub metadata: Vec<models::ScoreSlimChunks>,
}

impl GroupScoreSlimChunks {
    pub fn new(group_id: uuid::Uuid, metadata: Vec<models::ScoreSlimChunks>) -> GroupScoreSlimChunks {
        GroupScoreSlimChunks {
            group_id,
            metadata,
        }
    }
}

