/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.10.9
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupData {
    #[serde(rename = "groups")]
    pub groups: Vec<models::ChunkGroupAndFile>,
    #[serde(rename = "total_pages")]
    pub total_pages: i32,
}

impl GroupData {
    pub fn new(groups: Vec<models::ChunkGroupAndFile>, total_pages: i32) -> GroupData {
        GroupData {
            groups,
            total_pages,
        }
    }
}

