/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HeadQueries {
    #[serde(rename = "count")]
    pub count: i64,
    #[serde(rename = "query")]
    pub query: String,
}

impl HeadQueries {
    pub fn new(count: i64, query: String) -> HeadQueries {
        HeadQueries {
            count,
            query,
        }
    }
}

