/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocationPolygon {
    #[serde(rename = "exterior")]
    pub exterior: Vec<models::GeoInfo>,
    #[serde(rename = "interior", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interior: Option<Option<Vec<Vec<models::GeoInfo>>>>,
}

impl LocationPolygon {
    pub fn new(exterior: Vec<models::GeoInfo>) -> LocationPolygon {
        LocationPolygon {
            exterior,
            interior: None,
        }
    }
}

