/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PopularFiltersResponse {
    #[serde(rename = "popular_filters")]
    pub popular_filters: Vec<models::PopularFilters>,
}

impl PopularFiltersResponse {
    pub fn new(popular_filters: Vec<models::PopularFilters>) -> PopularFiltersResponse {
        PopularFiltersResponse {
            popular_filters,
        }
    }
}

