/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PopularFilters {
    #[serde(rename = "clause")]
    pub clause: String,
    #[serde(rename = "common_values")]
    pub common_values: std::collections::HashMap<String, i32>,
    #[serde(rename = "count")]
    pub count: i64,
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "filter_type")]
    pub filter_type: String,
}

impl PopularFilters {
    pub fn new(clause: String, common_values: std::collections::HashMap<String, i32>, count: i64, field: String, filter_type: String) -> PopularFilters {
        PopularFilters {
            clause,
            common_values,
            count,
            field,
            filter_type,
        }
    }
}

