/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QdrantSortBy {
    SortByField(Box<models::SortByField>),
    SortBySearchType(Box<models::SortBySearchType>),
}

impl Default for QdrantSortBy {
    fn default() -> Self {
        Self::SortByField(Default::default())
    }
}

