/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum RagAnalytics {
    #[serde(rename="RAGQueries")]
    RagQueries(Box<models::RagQueries>),
    #[serde(rename="RAGUsage")]
    RagUsage(Box<models::RagUsage>),
}

impl Default for RagAnalytics {
    fn default() -> Self {
        Self::RagQueries(Default::default())
    }
}


