/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecommendationAnalyticsFilter {
    #[serde(rename = "date_range", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_range: Option<Option<Box<models::DateRange>>>,
    #[serde(rename = "recommendation_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub recommendation_type: Option<Option<models::RecommendationType>>,
}

impl RecommendationAnalyticsFilter {
    pub fn new() -> RecommendationAnalyticsFilter {
        RecommendationAnalyticsFilter {
            date_range: None,
            recommendation_type: None,
        }
    }
}

