/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.8
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RecommendGroupChunkResponseTypes {
    RecommendGroupSlimChunksDto(Vec<models::GroupSlimChunksDto>),
    RecommendGroupChunksDto(Vec<models::GroupScoreChunkDto>),
}

impl Default for RecommendGroupChunkResponseTypes {
    fn default() -> Self {
        Self::RecommendGroupSlimChunksDto(Default::default())
    }
}

