/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecommendationStrategy {
    #[serde(rename = "average_vector")]
    AverageVector,
    #[serde(rename = "best_score")]
    BestScore,

}

impl ToString for RecommendationStrategy {
    fn to_string(&self) -> String {
        match self {
            Self::AverageVector => String::from("average_vector"),
            Self::BestScore => String::from("best_score"),
        }
    }
}

impl Default for RecommendationStrategy {
    fn default() -> RecommendationStrategy {
        Self::AverageVector
    }
}

