/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecommendType {
    #[serde(rename = "semantic")]
    Semantic,
    #[serde(rename = "full_text")]
    FullText,

}

impl ToString for RecommendType {
    fn to_string(&self) -> String {
        match self {
            Self::Semantic => String::from("semantic"),
            Self::FullText => String::from("full_text"),
        }
    }
}

impl Default for RecommendType {
    fn default() -> RecommendType {
        Self::Semantic
    }
}

