/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecommendationCtrMetrics1 {
    #[serde(rename = "filter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Option<Box<models::RecommendationAnalyticsFilter>>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl RecommendationCtrMetrics1 {
    pub fn new(r#type: Type) -> RecommendationCtrMetrics1 {
        RecommendationCtrMetrics1 {
            filter: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "recommendation_ctr_metrics")]
    RecommendationCtrMetrics,
}

impl Default for Type {
    fn default() -> Type {
        Self::RecommendationCtrMetrics
    }
}

