/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum RecommendationAnalytics {
    #[serde(rename="LowConfidenceRecommendations")]
    LowConfidenceRecommendations(Box<models::LowConfidenceRecommendations>),
    #[serde(rename="RecommendationQueries")]
    RecommendationQueries(Box<models::RecommendationQueries>),
}

impl Default for RecommendationAnalytics {
    fn default() -> Self {
        Self::LowConfidenceRecommendations(Default::default())
    }
}


