/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReturnQueuedChunk {
    SingleQueuedChunkResponse(Box<models::SingleQueuedChunkResponse>),
    BatchQueuedChunkResponse(Box<models::BatchQueuedChunkResponse>),
}

impl Default for ReturnQueuedChunk {
    fn default() -> Self {
        Self::SingleQueuedChunkResponse(Default::default())
    }
}

