/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScrollChunksResponseBody {
    #[serde(rename = "chunks")]
    pub chunks: Vec<models::ChunkMetadata>,
}

impl ScrollChunksResponseBody {
    pub fn new(chunks: Vec<models::ChunkMetadata>) -> ScrollChunksResponseBody {
        ScrollChunksResponseBody {
            chunks,
        }
    }
}

