/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.8
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchOverGroupsResponseBody {
    #[serde(rename = "group_chunks")]
    pub group_chunks: Vec<models::GroupScoreChunkDto>,
    #[serde(rename = "total_chunk_pages")]
    pub total_chunk_pages: i64,
}

impl SearchOverGroupsResponseBody {
    pub fn new(group_chunks: Vec<models::GroupScoreChunkDto>, total_chunk_pages: i64) -> SearchOverGroupsResponseBody {
        SearchOverGroupsResponseBody {
            group_chunks,
            total_chunk_pages,
        }
    }
}

