/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SearchSortBy {
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "latency")]
    Latency,
    #[serde(rename = "top_score")]
    TopScore,

}

impl ToString for SearchSortBy {
    fn to_string(&self) -> String {
        match self {
            Self::CreatedAt => String::from("created_at"),
            Self::Latency => String::from("latency"),
            Self::TopScore => String::from("top_score"),
        }
    }
}

impl Default for SearchSortBy {
    fn default() -> SearchSortBy {
        Self::CreatedAt
    }
}

