/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.10.9
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SearchMethod {
    #[serde(rename = "fulltext")]
    Fulltext,
    #[serde(rename = "semantic")]
    Semantic,
    #[serde(rename = "hybrid")]
    Hybrid,

}

impl ToString for SearchMethod {
    fn to_string(&self) -> String {
        match self {
            Self::Fulltext => String::from("fulltext"),
            Self::Semantic => String::from("semantic"),
            Self::Hybrid => String::from("hybrid"),
        }
    }
}

impl Default for SearchMethod {
    fn default() -> SearchMethod {
        Self::Fulltext
    }
}

