/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchSlimChunkQueryResponseBody {
    #[serde(rename = "score_chunks")]
    pub score_chunks: Vec<models::ScoreSlimChunks>,
    #[serde(rename = "total_chunk_pages")]
    pub total_chunk_pages: i64,
}

impl SearchSlimChunkQueryResponseBody {
    pub fn new(score_chunks: Vec<models::ScoreSlimChunks>, total_chunk_pages: i64) -> SearchSlimChunkQueryResponseBody {
        SearchSlimChunkQueryResponseBody {
            score_chunks,
            total_chunk_pages,
        }
    }
}

