/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchResponseBody {
    #[serde(rename = "chunks")]
    pub chunks: Vec<models::ScoreChunk>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "total_pages")]
    pub total_pages: i64,
}

impl SearchResponseBody {
    pub fn new(chunks: Vec<models::ScoreChunk>, id: uuid::Uuid, total_pages: i64) -> SearchResponseBody {
        SearchResponseBody {
            chunks,
            id,
            total_pages,
        }
    }
}

