/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.10.9
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchQueryEvent {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "dataset_id")]
    pub dataset_id: uuid::Uuid,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "latency")]
    pub latency: f32,
    #[serde(rename = "query")]
    pub query: String,
    #[serde(rename = "request_params")]
    pub request_params: String,
    #[serde(rename = "results")]
    pub results: Vec<models::ChunkMetadataStringTagSet>,
    #[serde(rename = "search_type")]
    pub search_type: String,
    #[serde(rename = "top_score")]
    pub top_score: f32,
}

impl SearchQueryEvent {
    pub fn new(created_at: String, dataset_id: uuid::Uuid, id: uuid::Uuid, latency: f32, query: String, request_params: String, results: Vec<models::ChunkMetadataStringTagSet>, search_type: String, top_score: f32) -> SearchQueryEvent {
        SearchQueryEvent {
            created_at,
            dataset_id,
            id,
            latency,
            query,
            request_params,
            results,
            search_type,
            top_score,
        }
    }
}

