/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.6
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SortOrder {
    #[serde(rename = "desc")]
    Desc,
    #[serde(rename = "asc")]
    Asc,

}

impl ToString for SortOrder {
    fn to_string(&self) -> String {
        match self {
            Self::Desc => String::from("desc"),
            Self::Asc => String::from("asc"),
        }
    }
}

impl Default for SortOrder {
    fn default() -> SortOrder {
        Self::Desc
    }
}

