/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagsWithCount {
    #[serde(rename = "count")]
    pub count: i64,
    #[serde(rename = "tag")]
    pub tag: String,
}

impl TagsWithCount {
    pub fn new(count: i64, tag: String) -> TagsWithCount {
        TagsWithCount {
            count,
            tag,
        }
    }
}

