/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.11.7
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkerEvent {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "dataset_id")]
    pub dataset_id: uuid::Uuid,
    #[serde(rename = "event_data")]
    pub event_data: String,
    #[serde(rename = "event_type")]
    pub event_type: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl WorkerEvent {
    pub fn new(created_at: String, dataset_id: uuid::Uuid, event_data: String, event_type: String, id: uuid::Uuid) -> WorkerEvent {
        WorkerEvent {
            created_at,
            dataset_id,
            event_data,
            event_type,
            id,
        }
    }
}

